# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xwing_data', '0012_auto_20170313_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwing_data.Pilot')),
                ('upgrades', models.ManyToManyField(to='xwing_data.Upgrade')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilots', models.ManyToManyField(to='matches.MatchPilot')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='squad_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_one', to='matches.Squad'),
        ),
        migrations.AddField(
            model_name='match',
            name='squad_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_two', to='matches.Squad'),
        ),
    ]
