# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpilot',
            name='upgrades',
            field=models.ManyToManyField(blank=True, to='xwing_data.Upgrade'),
        ),
    ]
