# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20170321_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='list_name',
            field=models.CharField(default='Unnamed List', max_length=200),
        ),
        migrations.AddField(
            model_name='squad',
            name='player_name',
            field=models.CharField(default='Joe Bloggs', max_length=200),
        ),
    ]
