# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20170321_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpilot',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
