# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwing_data', '0014_statisticset_skill'),
        ('matches', '0004_matchpilot_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwing_data.Upgrade')),
            ],
        ),
        migrations.AddField(
            model_name='matchpilot',
            name='stats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xwing_data.StatisticSet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchpilot',
            name='upgrades',
            field=models.ManyToManyField(blank=True, to='matches.MatchUpgrade'),
        ),
    ]
