# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 11:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20170322_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_minutes',
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 11, 5, 46, 800735, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
