# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20170322_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchupgrade',
            name='removed',
        ),
        migrations.AddField(
            model_name='matchupgrade',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
