# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20170322_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
