# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwing_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='xws',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ship',
            name='xws',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='pilot',
            unique_together=set([('xws', 'faction')]),
        ),
    ]
