# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwing_data', '0002_auto_20170313_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xwing_data.Stats'),
        ),
    ]
