# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwing_data', '0005_auto_20170313_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='StatisticSet',
        ),
        migrations.AddField(
            model_name='upgrade',
            name='ships',
            field=models.ManyToManyField(to='xwing_data.Ship'),
        ),
    ]
