# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwing_data', '0006_auto_20170313_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='size',
            field=models.ManyToManyField(to='xwing_data.BaseSize'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='range',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
