# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwing_data', '0008_auto_20170313_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='created',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='name',
        ),
    ]
