# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xwing_data', '0009_auto_20170313_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='grant',
            name='grant_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='xwing_data.GrantType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grant',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='grant',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
