# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('xwing_data', '0011_upgrade_grants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='grant_type',
        ),
        migrations.AddField(
            model_name='grant',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grant',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
