# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwing_data', '0012_auto_20170313_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='faction',
            field=models.ManyToManyField(blank=True, to='xwing_data.Faction'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='grants',
            field=models.ManyToManyField(blank=True, to='xwing_data.Grant'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='ships',
            field=models.ManyToManyField(blank=True, to='xwing_data.Ship'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='size',
            field=models.ManyToManyField(blank=True, to='xwing_data.BaseSize'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwing_data.SlotType'),
        ),
    ]
