# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwing_data', '0013_auto_20170321_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticset',
            name='skill',
            field=models.IntegerField(default=0),
        ),
    ]
