# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwing_data', '0014_statisticset_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticset',
            old_name='shields',
            new_name='shield',
        ),
    ]
