# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwing_data', '0017_auto_20170328_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
