# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwing_data', '0020_damagecard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='xws',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
